# Generated by Django 3.2.14 on 2022-07-29 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Amnat Charoen', 'อำนาจเจริญ'), ('Ang Thong', 'อ่างทอง'), ('Bangkok', 'กรุงเทพมหานคร'), ('Bueng Kan', 'บึงกาฬ'), ('Buri Ram', 'บุรีรัมย์'), ('Chachoengsao', 'ฉะเชิงเทรา'), ('Chai Nat', 'ชัยนาท'), ('Chaiyaphum', 'ชัยภูมิ'), ('Chanthaburi', 'จันทบุรี'), ('Chiang Mai', 'เชียงใหม่'), ('Chiang Rai', 'เชียงราย'), ('Chon Buri', 'ชลบุรี'), ('Chumphon', 'ชุมพร'), ('Kalasin', 'กาฬสินธุ์'), ('Kamphaeng Phet', 'กำแพงเพชร'), ('Kanchanaburi', 'กาญจนบุรี'), ('Khon Kaen', 'ขอนแก่น'), ('Krabi', 'กระบี่'), ('Lampang', 'ลำปาง'), ('Lamphun', 'ลำพูน'), ('Loei', 'เลย'), ('Lop Buri', 'ลพบุรี'), ('Mae Hong Son', 'แม่ฮ่องสอน'), ('Maha Sarakham', 'มหาสารคาม'), ('Mukdahan', 'มุกดาหาร'), ('Nakhon Nayok', 'นครนายก'), ('Nakhon Pathom', 'นครปฐม'), ('Nakhon Phanom', 'นครพนม'), ('Nakhon Ratchasima', 'นครราชสีมา'), ('Nakhon Sawan', 'นครสวรรค์'), ('Nakhon Si Thammarat', 'นครศรีธรรมราช'), ('Nan', 'น่าน'), ('Narathiwat', 'นราธิวาส'), ('Nong Bua Lam Phu', 'หนองบัวลำพู'), ('Nong Khai', 'หนองคาย'), ('Nonthaburi', 'นนทบุรี'), ('Pathum Thani', 'ปทุมธานี'), ('Pattani', 'ปัตตานี'), ('Phangnga', 'พังงา'), ('Phatthalung', 'พัทลุง'), ('Phayao', 'พะเยาว์'), ('Phetchabun', 'เพชรบูรณ์'), ('Phetchaburi', 'เพชรบุรี'), ('Phichit', 'พิจิตร'), ('Phitsanulok', 'พิษณุโลก'), ('Phra Nakhon Si Ayutthaya', 'พระนครศรีอยุธยา'), ('Phrae', 'แพร่'), ('Phuket', 'ภูเก็ต'), ('Prachin Buri', 'ปราจีนบุรี'), ('Prachuap Khiri Khan', 'ประจวบคีรีขันธ์'), ('Ranong', 'ระนอง'), ('Ratchaburi', 'ราชบุรี'), ('Rayong', 'ระยอง'), ('Roi Et', 'ร้อยเอ็ด'), ('Sa Kaeo', 'สระแก้ว'), ('Sakon Nakhon', 'สกลนคร'), ('Samut Prakan', 'สมุทรปราการ'), ('Samut Sakhon', 'สมุทรสาคร'), ('Samut Songkhram', 'สมุทรสงคราม'), ('Saraburi', 'สระบุรี'), ('Satun', 'สตูล'), ('Si Sa Ket', 'ศรีสะเกษ'), ('Sing Buri', 'สิงห์บุรี'), ('Songkhla', 'สงขลา'), ('Sukhothai', 'สุโขทัย'), ('Suphan Buri', 'สุพรรณบุรี'), ('Surat Thani', 'สุราษฎร์ธานี'), ('Surin', 'สุรินทร์'), ('Tak', 'ตาก'), ('Trang', 'ตรัง'), ('Trat', 'ตราด'), ('Ubon Ratchathani', 'อุบลราชธานี'), ('Udon Thani', 'อุดรธานี'), ('Uthai Thani', 'อุทัยธานี'), ('Uttaradit', 'อุตรดิตถ์'), ('Yala', 'ยะลา'), ('Yasothon', 'ยโสธร')], max_length=30, verbose_name='จังหวัด')),
                ('hospital_name', models.CharField(default='', max_length=50, verbose_name='Hospital')),
                ('opd', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='OPD (จำนวนคนต่อ 1 อาทิตย์)')),
                ('ipd', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='IPD (จำนวนครั้งในการ round ต่อ 1 อาทิตย์)')),
                ('er', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='ER (จำนวนคนต่อ 1 อาทิตย์)')),
                ('icu', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='ICU (จำนวนครั้งในการ round ต่อ 1 อาทิตย์)')),
                ('labour', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='Normal labour (จำนวนคนต่อ 1 อาทิตย์)')),
            ],
        ),
    ]
